# Projektinformationen
sonar.projectKey=scholvac_GraphicsView
sonar.projectName=GraphicsView
sonar.projectVersion=1.0
sonar.organization=scholvac
sonar.host.url=https://sonarcloud.io

# Quellcode-Analyse für ein Maven-Projekt
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=GraphicsViewCore/target/classes,GeoGraphicsView/target/classes
sonar.sources=GraphicsViewCore/src/main/java,GeoGraphicsView/src/main/java
sonar.tests=GraphicsViewCore/src/test/java,GeoGraphicsView/src/test/java
sonar.java.test.binaries=GraphicsViewCore/target/test-classes,GeoGraphicsView/target/test-classes
sonar.java.libraries=**/*.jar

# Coverage-Berichte einbinden
sonar.junit.reportPaths=GraphicsViewCore/target/surefire-reports,GeoGraphicsView/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=GraphicsViewCore/target/site/jacoco/jacoco.xml,GeoGraphicsView/target/site/jacoco/jacoco.xml

# Optionale Einstellungen
sonar.exclusions=**/target/**,**/*.xml,**/*.yaml,**/*.yml,**/*.json
sonar.test.inclusions=**/src/test/java/**/*.java
sonar.log.level=INFO
